name: Sync Discovered API with APIConnect
on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: ap-southeast-a.apiconnect.automation.ibm.com
  PLATFORM_API_PREFIX: platform-api-jne
  PROVIDER_ORG: dev4501662
  API_FILES: openapi2.yaml

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Validate API Governance (Spectral)
      run: |
        npm install -g @stoplight/spectral-cli
        spectral lint ${{ env.API_FILES }} --ruleset .spectral.yaml
        
    - name: Debug files
      run: |
        echo "API_FILES=${{ env.API_FILES }}"
        ls -l
    
    - uses: ibm-apiconnect/apic-discovery-action@main
      id: discover-apis
      with:
        api_host: ${{ env.API_HOST }}
        platform_api_prefix: ${{ env.PLATFORM_API_PREFIX }}
        provider_org: ${{ env.PROVIDER_ORG }}
        api_key: ${{ secrets.APICAPIKEY }}
        api_files: ${{ env.API_FILES }}
        resync_check: true
        insecure_skip_tls_verify: true
        
    - name: Display the action-result
      run: |
        RESULT='${{ steps.discover-apis.outputs.action-result }}'
        echo "Result from IBM: $RESULT"
        
        # Jika hasil kosong atau null, kita paksa error agar GitHub jadi MERAH
        if [ "$RESULT" == "[]" ] || [ "$RESULT" == "" ] || [ "$RESULT" == "null" ]; then
          echo "Koneksi berhasil, tapi tidak ada API yang terdaftar/terkirim ke IBM!"
          exit 1
        fi
